version: '2.1'
services:
  develop-spring-boot-admin:
    extends:
      file: docker-compose-base.yml
      service: base-spring-boot-admin
    container_name: ${CONTAINER_HOST_NAME:-standalone.spring-boot-admin}
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://user:user_pass@standalone.eureka:8761/eureka/}
    #- EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://user:user_pass@eureka-peer1:8761/eureka/,http://user:user_pass@eureka-peer2:8762/eureka/,http://user:user_pass@eureka-peer3:8763/eureka/}
    - LOGGING_LEVEL_ROOT=${LOGGING_LEVEL_ROOT:-INFO}
    - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME:-spring-boot-admin}
    #- SPRING_CLOUD_CLIENT_IPADDRESS=${SPRING_CLOUD_CLIENT_IPADDRESS}
    #- SPRING_CLOUD_CONSUL_ENABLED=${SPRING_CLOUD_CONSUL_ENABLED:-false}
    - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-discovery}
    hostname: ${CONTAINER_HOST_NAME:-standalone.spring-boot-admin}
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.99}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::99}
    ports:
    - "${EUREKA_INSTANCE_NONSECUREPORT:-1111}:${SERVER_PORT:-1111}"
    volumes:
    - data:/home/alpine/data
    #- tmp:/tmp

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
  tmp:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/tmp
      o: bind
