version: '2.1'
services:
  base-spring-boot-admin:
    command: []



    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://user:user_pass@standalone.eureka:8761/eureka/}
    - EUREKA_INSTANCE_NONSECUREPORT=${EUREKA_INSTANCE_NONSECUREPORT:-1111}
    - HOST_IPADDRESS=${HOST_IPADDRESS}
    - JAVA_DEBUG_PORT=${JAVA_DEBUG_PORT:-}
    - JAVA_OPTS=${JAVA_OPTS:-}
    - LOG_PATH=${LOG_PATH:/home/alpine/data/logs}
    - LOG_FILE_MAX_HISTORY=${LOG_FILE_MAX_HISTORY:-30}
    - LOG_FILE_MAX_SIZE=${LOG_FILE_MAX_SIZE:-32}
    - LOGGING_LEVEL_ROOT=${LOGGING_LEVEL_ROOT:-INFO}
    #- LOGSTASH_DESTINATION=${LOGSTASH_DESTINATION}
    - SERVER_PORT=${SERVER_PORT:-1111}
    #- SPRING_CLOUD_CONFIG_LABEL=${SPRING_CLOUD_CONFIG_LABEL}
    #- SPRING_CLOUD_CONFIG_PASSWORD=${SPRING_CLOUD_CONFIG_PASSWORD}
    #- SPRING_CLOUD_CONFIG_USERNAME=${SPRING_CLOUD_CONFIG_USERNAME}
    #- SPRING_CLOUD_CONSUL_ENABLED=${SPRING_CLOUD_CONSUL_ENABLED:-false}
    #- SPRING_CLOUD_CONSUL_HOST=${SPRING_CLOUD_CONSUL_HOST}
    #- SPRING_CLOUD_CONSUL_PORT=${SPRING_CLOUD_CONSUL_PORT}
    - SPRING_CLOUD_INETUTILS_PREFERREDNETWORKS=${SPRING_CLOUD_INETUTILS_PREFERREDNETWORKS}
    - SPRING_CLOUD_INETUTILS_IGNOREDINTERFACES=${SPRING_CLOUD_INETUTILS_IGNOREDINTERFACES}
    - SPRING_MAIL_HOST=${SPRING_MAIL_HOST:-smtp.example.com}
    - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD:-smtp_user_pass}
    - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME:-smtp_user}
    - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-}
    - TURBINE_APPCONFIG=${TURBINE_APPCONFIG:-spring-boot-admin}
    - TURBINE_CLUSTERNAMEEXPRESSION=${TURBINE_CLUSTERNAMEEXPRESSION:-new String("default")}
    - TURBINE_COMBINEHOSTPORT=${TURBINE_COMBINEHOSTPORT:-true}
    image: ${IMAGE_PREFIX:-cloudready/}spring-boot-admin:${IMAGE_TAG:-1.5.7}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/spring-boot-admin/standalone}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.spring-boot-admin}
    ports:
    - "${EUREKA_INSTANCE_NONSECUREPORT:-1111}:${SERVER_PORT:-1111}"
    restart: always
