version: '2.1'
services:
  develop-spring-boot-admin:
    extends:
      file: docker-compose-base.yml
      service: base-spring-boot-admin
    container_name: ${CONTAINER_HOST_NAME:-spring-boot-admin}
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://user:user_pass@standalone.eureka:8761/eureka/}
    - LOGGING_LEVEL_ROOT=${LOGGING_LEVEL_ROOT:-DEBUG}
    - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME:-spring-boot-admin}
    #- SPRING_CLOUD_CONFIG_LABEL=${SPRING_CLOUD_CONFIG_LABEL:-develop}
    #- SPRING_CLOUD_CONFIG_PASSWORD=${SPRING_CLOUD_CONFIG_PASSWORD:-admin_pass}
    #- SPRING_CLOUD_CONFIG_USERNAME=${SPRING_CLOUD_CONFIG_USERNAME:-admin}
    #- SPRING_CLOUD_CONSUL_ENABLED=${SPRING_CLOUD_CONSUL_ENABLED:-false}
    - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-}
    hostname: ${CONTAINER_HOST_NAME:-spring-boot-admin}
    #network_mode: bridge
    networks:
      local-network:
        ipv4_address: 172.16.238.99
        #ipv6_address: 2001:3984:3989::99
    ports:
    - "${EUREKA_INSTANCE_NONSECUREPORT:-1111}:${SERVER_PORT:-1111}"
    volumes:
    - data:/home/alpine/data
    #- tmp:/tmp

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
  tmp:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/tmp
      o: bind
