version: '2.1'
services:
  base-spring-boot-admin:
    command: []



    environment:

    - EUREKA_CLIENT_ENABLED=${EUREKA_CLIENT_ENABLED:-true}
    #- EUREKA_CLIENT_REGISTERWITHEUREKA=${EUREKA_CLIENT_REGISTERWITHEUREKA:-true}
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://user:user_pass@standalone.eureka:8761/eureka/}
    - EUREKA_INSTANCE_HOSTNAME=${EUREKA_INSTANCE_HOSTNAME:-standalone.spring-boot-admin}
    #- EUREKA_INSTANCE_IPADDRESS=${EUREKA_INSTANCE_IPADDRESS}
    - EUREKA_INSTANCE_NONSECUREPORT=${EUREKA_INSTANCE_NONSECUREPORT:-1111}

    - HOST_IPADDRESS=${HOST_IPADDRESS}
    - JAVA_OPTS=${JAVA_OPTS:-}
    - JPDA_ADDRESS=${JPDA_ADDRESS:-}
    - LOG_PATH=${LOG_PATH:-/home/alpine/data/logs}
    - LOG_FILE_MAX_HISTORY=${LOG_FILE_MAX_HISTORY:-30}
    - LOG_FILE_MAX_SIZE=${LOG_FILE_MAX_SIZE:-32}
    - LOGGING_LEVEL_ROOT=${LOGGING_LEVEL_ROOT:-INFO}
    - SERVER_ADDRESS=${SERVER_ADDRESS:-}
    - SERVER_PORT=${SERVER_PORT:-1111}
    - SERVICE_REGISTER_ENABLE=${SERVICE_REGISTER_ENABLED:-true}

    - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME:-spring-boot-admin}

    - SPRING_BOOT_ADMIN_CLIENT_PREFERIP=${SPRING_BOOT_ADMIN_CLIENT_PREFERIP:-false}
    #- SPRING_BOOT_ADMIN_PROBEDENDPOINTS=${SPRING_BOOT_ADMIN_PROBEDENDPOINTS:-health,env,metrics,httptrace:trace,threaddump:dump,jolokia,info,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents}

    # A component required a bean of type 'org.springframework.cloud.stream.binder.Binder' that could not be found.
    # Consider defining a bean of type 'org.springframework.cloud.stream.binder.Binder' in your configuration.
    # see: https://github.com/spring-cloud/spring-cloud-consul/issues/309
    - SPRING_CLOUD_BUS_ENABLED=${SPRING_CLOUD_BUS_ENABLED:-false}
    - SPRING_CLOUD_CLIENT_HOSTNAME=${EUREKA_INSTANCE_HOSTNAME:-standalone.spring-boot-admin}
    - SPRING_CLOUD_CLIENT_IPADDRESS=${SPRING_CLOUD_CLIENT_IPADDRESS}

    - SPRING_CLOUD_CONSUL_ENABLED=${SPRING_CLOUD_CONSUL_ENABLED:-false}
    #- SPRING_CLOUD_CONSUL_HOST=${SPRING_CLOUD_CONSUL_HOST}
    #- SPRING_CLOUD_CONSUL_PORT=${SPRING_CLOUD_CONSUL_PORT}

    - SPRING_CLOUD_INETUTILS_PREFERREDNETWORKS=${SPRING_CLOUD_INETUTILS_PREFERREDNETWORKS}
    - SPRING_CLOUD_INETUTILS_IGNOREDINTERFACES=${SPRING_CLOUD_INETUTILS_IGNOREDINTERFACES}

    #- SPRING_CLOUD_SERVICEREGISTRY_AUTOREGISTRATION_ENABLED=${SPRING_CLOUD_SERVICEREGISTRY_AUTOREGISTRATION_ENABLED:-true}

    - SPRING_MAIL_HOST=${SPRING_MAIL_HOST:-smtp.example.com}
    - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD:-smtp_user_pass}
    - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME:-smtp_user}

    - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-discovery}
    - SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD:-admin_pass}

    - TURBINE_APPCONFIG=${TURBINE_APPCONFIG:-spring-boot-admin}
    - TURBINE_CLUSTERNAMEEXPRESSION=${TURBINE_CLUSTERNAMEEXPRESSION:-new String("default")}
    - TURBINE_COMBINEHOSTPORT=${TURBINE_COMBINEHOSTPORT:-true}
    image: ${IMAGE_PREFIX:-@docker.image.prefix@}spring-boot-admin:${IMAGE_TAG:-@project.version@}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/spring-boot-admin/standalone}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.spring-boot-admin}
    ports:
    - "${EUREKA_INSTANCE_NONSECUREPORT:-1111}:${SERVER_PORT:-1111}"
    restart: always
